# .github/workflows/pytest.yaml
name: PyTest
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  test:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Install NiftyReg
        run: |
          git clone https://git.code.sf.net/p/niftyreg/git niftyreg-git
          cd niftyreg-git
          mkdir build
          cd build
          cmake ../
          sudo make
          sudo make install

      - name: Run tests
        run: |
          python setup.py install
          pytest
