# .github/workflows/pytest.yaml
name: PyTest
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Clone NiftyReg
        uses: actions/checkout@v3
        with:
          repository: KCL-BMEIS/niftyreg
          path: niftyreg

      - name: Install NiftyReg
        run: |
          cd niftyreg
          mkdir build
          cd build
          cmake ../
          sudo make
          sudo make install

      - name: Run tests
        run: |
          python setup.py install
          pytest
